AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.

Resources:
  LexV2Bot:
    Type: AWS::Lex::Bot
    Properties:
        Name: callbackPhoneNumberUpdateLexTestV1
        Description: Callback Phone Number Update Lex Test V1
        IdleSessionTTLInSeconds: 300
        RoleArn: "arn:aws:iam::750344256621:role/aws-service-role/lexv2.amazonaws.com/AWSServiceRoleForLexV2Bots_lex-bot-deployment-test-role"
        DataPrivacy: 
          ChildDirected: false #  true | false
Outputs:
  BotId:
    Description: The ID of the Lex bot
    Value: !GetAtt LexV2Bot.Id
  # MyIntent:
  #   Type: AWS::Lex::Bot Intent
  #   Name: FallbackIntent
  #   Description: Default intent when no other intent matches


  # MyIntent:
  #   Type: AWS::Lex::Intent
  #   Properties:
  #     Name: FallbackIntent
  #     Description: Default intent when no other intent matches
  #     SampleUtterances:
  #       - "sample utterance"
  #     Slots:
  #       - Name: c
  #         SlotType: AMAZON.Number
  #         SlotConstraint: Required
  #         ValueElicitationSetting:
  #           PromptSpecification:
  #             Messages:
  #               - ContentType: PlainText
  #                 Content: "Please provide the value for amount"

  # MySlotType:
  #   Type: AWS::Lex::SlotType
  #   Properties:
  #     Name: MySlotType
  #     Description: My Slot Type
  #     SlotTypeValues:
  #       - SampleValue:
  #           Value: "200"