AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.

Resources:
  LexV2Bot:
    Type: AWS::Lex::Bot
    Properties:
        Name: callbackPhoneNumberUpdateLexTestV1
        Description: Callback Phone Number Update Lex Test V1
        IdleSessionTTLInSeconds: 300
        RoleArn: "arn:aws:iam::750344256621:role/aws-service-role/lexv2.amazonaws.com/AWSServiceRoleForLexV2Bots_lex-bot-deployment-test-role"
        DataPrivacy: 
          ChildDirected: false #  true | false
Outputs:
  BotId:
    Description: The ID of the Lex bot #  The ID of the Lex bot
    Value: !GetAtt LexV2Bot.Id #  The ID of the Lex bot