name: Deploy Lex V2 Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::750344256621:role/CII-GitHub-Account-IAM-Role
        role-duration-seconds: 900 # optional, defaults to 3600 seconds
        aws-region: us-east-1 # use your region here.

    - name: Install AWS SAM CLI
      run: |
        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        sam --version

    - name: Deploy Lex V2 Bot
      run: |
        cd src/callbackPhoneNumberUpdate
        sam build
        sam deploy --guided